### ISSUE TITLE
ERROR: "Corrupted zip: can't find end of central directory"

### ISSUE THREAD

**Issue by lmadden94** [shawmut/DataPreflight#10]
Error that was occurring with John Q Sample database(s). Text file attached. Can't upload CSV.

[John Q Samples.txt](https://github.com/dominickp/DataPreflight/files/147369/John.Q.Samples.txt)

Error: Corrupted zip : can't find end of central directory
    at Object.ZipEntries.readEndOfCentral (C:\Repo\DataPreflight\node_modules\j\node_modules\xlsx\node_modules\jszip\lib\zipEntries.js:135:19)
    at Object.ZipEntries.load (C:\Repo\DataPreflight\node_modules\j\node_modules\xlsx\node_modules\jszip\lib\zipEntries.js:197:14)
    at Object.ZipEntries (C:\Repo\DataPreflight\node_modules\j\node_modules\xlsx\node_modules\jszip\lib\zipEntries.js:21:14)
    at Object.module.exports [as load](C:RepoDataPreflightnode_modulesjnode_modulesxlsxnode_modulesjsziplibload.js:11:18)
    at Object.JSZip (C:\Repo\DataPreflight\node_modules\j\node_modules\xlsx\node_modules\jszip\lib\index.js:39:14)
    at readSync (C:\Repo\DataPreflight\node_modules\j\node_modules\xlsx\xlsx.js:5151:20)
    at Object.readFileSync [as readFile](C:RepoDataPreflightnode_modulesjnode_modulesxlsxxlsx.js:5159:9)
    at Object.readFileSync [as readFile](C:RepoDataPreflightnode_modulesjj.js:24:33)
    at C:\Repo\DataPreflight\src\model\preflightModel.js:145:33
    at new PreflightModel (C:\Repo\DataPreflight\src\model\preflightModel.js:161:6)

**Comment by dominickp** [comment]
Not sure why this fails to parse but now it will simply not preflight: 27a0540c58dc0c2349c2ecb9bff950791559ad7b
