### ISSUE TITLE
Crash when preflighting a single file

### ISSUE THREAD

**Issue by dominickp** [shawmut/DataPreflight#16]
TypeError: initCb is not a function
    at /Users/dkelly/Desktop/shamut/DataPreflight/src/js/preflightFile.js:84:25
    at model.writeFile (/Users/dkelly/Desktop/shamut/DataPreflight/src/js/preflightFile.js:42:9)
    at /Users/dkelly/Desktop/shamut/DataPreflight/src/js/preflightFile.js:81:27
    at /Users/dkelly/Desktop/shamut/DataPreflight/src/js/preflightFile.js:30:21
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by dominickp** [comment]
Fixed in 54dca8fcb239da5f236abfedb279adc666e078f2
